# Generated by Django 4.1.6 on 2023-03-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGeneral', '0002_noticias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
